# Generated by Django 4.2.1 on 2023-05-21 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="SkillModel",
        ),
    ]
