# Generated by Django 4.2.1 on 2023-05-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_skill_skillmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcreatemodel",
            name="vacancy_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
