# Generated by Django 4.2.1 on 2023-05-22 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_jobcreatemodel_vacancy_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobcreatemodel",
            name="requirements",
        ),
    ]
