# Generated by Django 4.2.1 on 2023-05-22 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_jobcreatemodel_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobcreatemodel",
            name="skills",
        ),
        migrations.DeleteModel(
            name="SkillModel",
        ),
    ]
