# Generated by Django 4.2.1 on 2023-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_jobcreatemodel_skills_delete_skillmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymodel",
            name="description",
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="image",
            field=models.ImageField(
                default="path/to/default_image.jpg", upload_to="category_images"
            ),
        ),
    ]
