# Generated by Django 4.2.1 on 2023-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_categorymodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcreatemodel",
            name="nature",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("Featured", "Featured"),
                ],
                max_length=20,
            ),
        ),
    ]
