# Generated by Django 4.2.1 on 2023-05-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_contactmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyJobModel",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("portfolio", models.URLField()),
                ("resume", models.FileField(upload_to="resumes/")),
                ("cover_letter", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
