# Generated by Django 4.2.1 on 2023-05-25 05:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_applyjobmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjobmodel",
            name="company",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applyjobmodel",
            name="job",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.jobcreatemodel",
            ),
        ),
        migrations.AddField(
            model_name="applyjobmodel",
            name="jobtitle",
            field=models.CharField(default="Default Job Title", max_length=255),
            preserve_default=False,
        ),
    ]
